apiVersion: appprotect.f5.com/v1beta1
kind: APUserSig
metadata:
  name: hackerz-sig
spec:
  signatures:
  - accuracy: medium
    attackType:
      name: Brute Force Attack
    description: Medium accuracy user defined signature with tag (BadActors)
    name: Hacker_medium_acc
    risk: medium
    rule: content:"hackerz"; nocase;
    signatureType: request
    systems:
    - name: Microsoft Windows
    - name: Unix/Linux
  tag: BadActors
